### ISSUE TITLE
confluenceParentId -> Page Not Found

### ISSUE THREAD

**Issue by Deastrom** [markdown-confluence/markdown-confluence#461]
Getting a super long error when trying to publish, but it's essentially 404.

"The page you were trying to reach could not be found"

I have double, triple checked the page idea and base url.  My api key works with other functions I'm using.

The biggest diff I see between what I'm doing and what the docs say is that my `confluenceBaseUrl` ends with a `/wiki`. `https://<biz>.atlassian.net/wiki`

Are there prerequisites to using this tool that I'm not seeing?

**Comment by Deastrom** [comment]
dropped the /wiki... did that before, but received a new error "No Paths Provided" and assumed it didn't work.

now the pages are created, but the it's not publishing ... 

getting Permission Denied errors in the cli through docker run... which is just a simple user permissions error. should be able to figure it out from here.

**Comment by Deastrom** [comment]
got it working by adding `-u "1000:1000"` to my docker run (for some reason it had me in there as uid 999:999. Got it working locally doing that. Got it working up in Gitlab without any additional changes.

```yaml
publish to confluence:
  image: ghcr.io/markdown-confluence/publish:5.4
  stage: deploy
  script:
    - node /app/index.js
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
```

works like a champ, thankyou for the project.
